#!/bin/sh

cp ./eg_ost/* ./initial
rm ./initial/eg_ost.ino

cp ./eg_ost/* ./eg_west
rm ./eg_west/eg_ost.ino

cp ./eg_ost/* ./og_west
rm ./og_west/eg_ost.ino

cp ./eg_ost/* ./og_ost
rm ./og_ost/eg_ost.ino

cp ./eg_ost/* ./ug
rm ./ug/eg_ost.ino

cp ./eg_ost/* ./gr_node32
rm ./gr_node_mcu/eg_ost.ino
rm ./gr_node_mcu/handler_t.ino
rm ./gr_node_mcu/communication.ino
rm ./gr_node_mcu/handler_watchdog.ino
rm ./gr_node_mcu/handler_r.ino


cp ./eg_ost/* ./ch_node32
rm ./ch_node32/eg_ost.ino
rm ./ch_node32/handler_t.ino
rm ./ch_node32/communication.ino
rm ./ch_node32/handler_watchdog.ino
cp ./gr_node32/handler_watchdog_esp32.ino     ./ch_node32
cp ./gr_node32/handler_t_esp32.ino          ./ch_node32


