#!/bin/sh

cp ./eg_ost/* ./initial
rm ./initial/eg_ost.ino

cp ./eg_ost/* ./eg_west
rm ./eg_west/eg_ost.ino

cp ./eg_ost/* ./og_west
rm ./og_west/eg_ost.ino

cp ./eg_ost/* ./og_ost
rm ./og_ost/eg_ost.ino

cp ./eg_ost/* ./ug
rm ./ug/eg_ost.ino

cp ./eg_ost/* ./gr
rm ./gr/eg_ost.ino
rm ./gr/handler_r.ino

