#!/bin/sh

cp ./eg_ost/* ./initial
rm ./initial/eg_ost.ino

cp ./eg_ost/* ./eg_west
rm ./eg_west/eg_ost.ino

cp ./eg_ost/* ./og_west
rm ./og_west/eg_ost.ino

cp ./eg_ost/* ./og_ost
rm ./og_ost/eg_ost.ino

cp ./eg_ost/* ./ug
rm ./ug/eg_ost.ino

cp ./eg_ost/* ./gr_node_mcu
rm ./gr_node_mcu/eg_ost.ino
rm ./gr_node_mcu/handler_t.ino
rm ./gr_node_mcu/communication.ino
rm ./gr_node_mcu/handler_watchdog.ino
rm ./gr_node_mcu/handler_r.ino


cp ./eg_ost/* ./ch_node_mcu
rm ./ch_node_mcu/eg_ost.ino
rm ./ch_node_mcu/handler_t.ino
rm ./ch_node_mcu/communication.ino
rm ./ch_node_mcu/handler_watchdog.ino
cp ./gr_node_mcu/communication_node_mcu.ino     ./ch_node_mcu
cp ./gr_node_mcu/handler_watchdog_mcu.ino       ./ch_node_mcu
cp ./gr_node_mcu/handler_t_nodemcu.ino          ./ch_node_mcu


